/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WritingRouteImport } from './routes/writing'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as FilmsRouteImport } from './routes/films'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntryCategorySlugRouteImport } from './routes/entry.$category.$slug'

const WritingRoute = WritingRouteImport.update({
  id: '/writing',
  path: '/writing',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const FilmsRoute = FilmsRouteImport.update({
  id: '/films',
  path: '/films',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryCategorySlugRoute = EntryCategorySlugRouteImport.update({
  id: '/entry/$category/$slug',
  path: '/entry/$category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/films': typeof FilmsRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/photography': typeof PhotographyRoute
  '/writing': typeof WritingRoute
  '/entry/$category/$slug': typeof EntryCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/films': typeof FilmsRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/photography': typeof PhotographyRoute
  '/writing': typeof WritingRoute
  '/entry/$category/$slug': typeof EntryCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/films': typeof FilmsRoute
  '/notebook': typeof NotebookRoute
  '/notes': typeof NotesRoute
  '/photography': typeof PhotographyRoute
  '/writing': typeof WritingRoute
  '/entry/$category/$slug': typeof EntryCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/films'
    | '/notebook'
    | '/notes'
    | '/photography'
    | '/writing'
    | '/entry/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/films'
    | '/notebook'
    | '/notes'
    | '/photography'
    | '/writing'
    | '/entry/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/films'
    | '/notebook'
    | '/notes'
    | '/photography'
    | '/writing'
    | '/entry/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FilmsRoute: typeof FilmsRoute
  NotebookRoute: typeof NotebookRoute
  NotesRoute: typeof NotesRoute
  PhotographyRoute: typeof PhotographyRoute
  WritingRoute: typeof WritingRoute
  EntryCategorySlugRoute: typeof EntryCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/writing': {
      id: '/writing'
      path: '/writing'
      fullPath: '/writing'
      preLoaderRoute: typeof WritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/films': {
      id: '/films'
      path: '/films'
      fullPath: '/films'
      preLoaderRoute: typeof FilmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$category/$slug': {
      id: '/entry/$category/$slug'
      path: '/entry/$category/$slug'
      fullPath: '/entry/$category/$slug'
      preLoaderRoute: typeof EntryCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FilmsRoute: FilmsRoute,
  NotebookRoute: NotebookRoute,
  NotesRoute: NotesRoute,
  PhotographyRoute: PhotographyRoute,
  WritingRoute: WritingRoute,
  EntryCategorySlugRoute: EntryCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
